version: '3.9'
services:
  web:
    image: "task-tracker-frontend"
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
      args:
        # - API_ROOT=https://example.com
    ports:
      - 8080:80
    restart: unless-stopped
